Portfolio mobile first #5
Carl2678/Portfolio-mobile-first pull request #1
Opened 2022-10-29 19:12 UTC by Carl2678

-Add templates
-configure linters

2022-10-29 20:09 UTC, Lizdev-05 requested changes
Hi @Carl2678, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have linters installed properly. Please reinstall your linters and add node_module to gitignore file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-01 04:02 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @Carl2678 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Your logo looks really good 😉.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 04:02 UTC, Gopxfs commented on index.html
> +        </header>
Great job setting a `header` with a `nav` element. Please consider that your logo should be outside the `nav` element and shouldn't occupy 100% width 😉. Inside your `nav`, you should put the hamburger menu, as displayed on the template:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/199153898-055594a4-f47c-44f8-8a79-af06571838f1.png)  | ![image](https://user-images.githubusercontent.com/42799579/199153929-49787691-e7a8-4877-8c9c-fa6016df737c.png)  |

```html 
<header> 
  <a href=#>Your beautiful logo</a>  

  <nav> 
    Hamburger icon 
  </nav> 
</header> 
```

2022-11-01 04:02 UTC, Gopxfs commented on style.css
> +  top: 92px;
Please consider that you should follow the same margins as displayed in the design 😄:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/199154341-0928988a-969d-46af-ad99-20a1f1b0a4d3.png)  | ![image](https://user-images.githubusercontent.com/42799579/199154308-73b76bbc-bbce-4227-9ceb-b19ea80cab48.png)  |

This also applies to the margin inside your boxes:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/199155267-82738909-63f0-4a12-b34e-cbe7699cf493.png)  | ![image](https://user-images.githubusercontent.com/42799579/199155245-dc1c66d5-9694-4293-9d67-890e4c2e7f95.png)  |

Kindly notice that the origin design have spacing between the text and the box 'walls' 😉.

2022-11-01 04:02 UTC, Gopxfs commented on index.html
> +                <h4>LET'S CONNECT</4>
Please note that your website text should use the same fonts as the ones in the design 😃. To check them, you can select the text that you want on Figma and the typography will be displayed to you:
![image](https://user-images.githubusercontent.com/42799579/199154620-e1d0eed9-1bb4-4e0d-934d-8d0e6ac6e1cf.png)
> Note: you should also use the same line height, font size, font weight, etc... Kindly follow the whole typography 😉.

2022-11-01 04:02 UTC, Gopxfs commented on index.html
> +                <div id="contact">
Please take into account that you should follow the same color scheme as the one displayed on Figma 😉. To do so, you can always select any element and check for specific details. In this case, kindly update your 'Let's connect' & `h1` text colors:
| `h1`  | Let's connect |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/199155010-c44e69b2-6696-4f4c-b44e-52c0fe817e73.png)  | ![image](https://user-images.githubusercontent.com/42799579/199155057-82b6dd05-8844-4311-b741-0d9b2bba525a.png)  |

2022-11-01 04:02 UTC, Gopxfs commented on style.css
> +  height: 5410px;
[OPTIONAL] I've noticed that you used a fixed width for your whole project. Please take into account that, although this is the width displayed on the design, you shouldn't use a fixed width for your projects (it is just the width of the device used for the screenshot). I will explain: 

The idea of Responsive Web Design is that your webpage should adapt itself to any device/window size that opens it. In other words, it is responsive. This means that using a fixed width for your sections will break this responsiveness, causing a static view to be formed. So, what can you do about it? Simple, use percentages! Instead of `width: 327px`, use `width: 100%`. This will make your project stretches to any window size that you can imagine 😉. If you need a smaller section, use a lower percentage. If you really need to use a fixed width, keep in mind that it may break the responsiveness of your webpage 😄! 

_But, my mobile version looks horrible stretched to a big window 😢._ 

Don't worry about this! There is a thing called [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) that will allow you to add different styling to different window sizes in the future. Then, you can edit a mobile version and a desktop version for your apps, depending on the window size 😄. But for now, you should focus on the mobile version 😉. 

With a fixed width, even on mobile screens, it doesn't fit correctly. Check your project on an iPhone SE: 
![image](https://user-images.githubusercontent.com/42799579/199155448-cc1e4606-72d8-4ddf-80f2-2d3e742e3df0.png)

If you are interested to learn more about it, check [this link](https://www.w3schools.com/html/html_responsive.asp) and this [youtube video](https://www.youtube.com/watch?v=VQraviuwbzU). 

Good luck and keep coding 😃!

2022-11-01 04:02 UTC, Gopxfs commented on style.css
> +    url("images/Ellipse\ 15.png");
Great job getting the correct background images! It will look even better if you display these images accordingly to the Figma design:
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/199155742-056ef24d-98e7-4ea8-aec4-3c7b2ffe5ba9.png)  | ![image](https://user-images.githubusercontent.com/42799579/199155721-15d9ee9c-29d8-431c-a82f-a5f4545b6ccc.png)  |


> Keep in mind that this project's goal is to improve your ability to follow design guidelines (imagine Microverse as a client requesting a website) 😉.

2022-11-01 21:16 UTC, frank1738 requested changes
Hi @Carl2678 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


<img src="https://media2.giphy.com/media/1xVbRS6j52YSzp9P7N/giphy.gif"/>


## Highlights

✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 21:16 UTC, frank1738 commented on index.html
> +  </nav>
- [ ] I noticed that you had made changes to the `logo` but couldn't position the hamburger button to the right. I would recommend that you apply these styles to the overall container that contains the `logo` and `hamburger` button
- [ ] ` display: flex `
- [ ]  `justify-content: space between`

2022-11-01 21:16 UTC, frank1738 commented on index.html
> +                     <li class="icon"><a href="#" target="_blank"><img src="images/Angel.svg" alt="Angel list link"></a></li>
- [ ] Kindly give your social links a `margin-top` and align them to the left to match the Figma design. Also adjust the `let's connect` text to match the original design

![image](https://user-images.githubusercontent.com/98453979/199342521-4ace0a38-4bc4-4acb-9c8c-4b749c8a631e.png)

### Checkout Figma design

![image](https://user-images.githubusercontent.com/98453979/199342707-f65c529d-70c2-4469-9ae1-d7182e4881a1.png)

2022-11-02 03:21 UTC, emmiiorji approved these changes
Hi @Carl2678, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Red-approved](https://user-images.githubusercontent.com/20554583/199362837-208e4c72-b63b-4cdb-a8ed-cebfdac94960.gif)

## Good Highlights

- Linter checks are passing
- Adherence to GitHub flow
- Requested changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 05:03 UTC, merged